FROM arm32v7/rust

RUN apt-get update

#TODO TRIM?
#ENV NIGHTLY_DATE 2019-05-25

ENV RUST_BACKTRACE 1

### TODO TRY USING STABLE
# ⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️
# ⚠️ specify a known, working version of nightly 
# ⚠️ to avoid Signal 11 mem alloc failures 😩🔥
# ⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️
# RUN rustup default nightly-${NIGHTLY_DATE}

COPY . .

RUN cargo install --path .

RUN sh shrink_docker_image.sh

CMD ["led_status_helper"]
