version: '3'
services:
  redis_aggregator:
    build: redis_aggregator/.
    volumes:
      - "$PWD/redis_aggregator_volume:/data"
    depends_on:
      - "redis"
    command: ["./wait-for-it.sh", "redis:36379", "--", "redis_aggregator"]
  redis:
    image: "arm32v7/redis" 
    ports:
      - "36379:6379"
    volumes:
      - "$PWD/redis_volume:/data"
