version: '3'
services:
  redis:
    build: redis/.
  mosquitto:
    build: mosquitto/.
    ports:
     - "1883:1883"
     - "8883:8883"
  telegraf:  
    image: "telegraf:1.6"
  influx:
    image: "influxdb:influxdb"
