version: '3'
services:
  grafana:
    image: "fg2it/grafana-armhf:v5.1.4"
    ports:
      - "3000:3000"
    volumes:
            #- "$PWD/grafana_volume/etc/grafana:/etc/grafana"
      - "$PWD/grafana_volume/var/lib/grafana:/var/lib/grafana"
  rocket:
    build: rocket/.
    ports:
      - "0.0.0.0:80:80"
  redis:
    build: redis/.
    ports:
      - "36379:6379"
  mosquitto:
    build: mosquitto/.
    ports:
     - "1883:1883"
     - "8883:8883"
  telegraf:  
    image: "telegraf:1.6"
    volumes:
      - "$PWD/telegraf_volume/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
  influxdb:
    image: "influxdb:latest"
    ports:
      - "8086:8086"
    volumes:
      - "$PWD/influxdb_volume:/var/lib/influxdb"
