version: '3'
services:
  redis_aggregator:
    build: redis_aggregator/.
    volumes:
      - "/var/volumes/redis_aggregator_volume:/data"
    depends_on:
      - "redis"
    command: ["./wait-for-it.sh", "redis:36379", "--", "redis_aggregator"]
  grafana:
    image: "fg2it/grafana-armhf:v5.1.4"
    ports:
      - "3000:3000"
    volumes:
      - "/var/volumes/grafana_volume/etc/grafana:/etc/grafana"
      - "/var/volumes/grafana_volume/var/lib/grafana:/var/lib/grafana"
  redis:
    image: "arm32v7/redis" 
    ports:
      - "36379:6379"
    volumes:
      - "/var/volumes/redis_volume:/data"
  mosquitto:
    build: mosquitto/.
    ports:
      - "1883:1883"
      - "8883:8883"
  telegraf:  
    image: "telegraf:1.6"
    volumes:
      - "/var/volumes/telegraf_volume/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
  influxdb:
    image: "influxdb:latest"
    ports:
      - "8086:8086"
    volumes:
      - "/var/volumes/influxdb_volume:/var/lib/influxdb"

