[package]
name = "sensor_tracker"
version = "0.3.1"
authors = ["Terkwood <metaterkhorn@gmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.13"
envy = "0.3"
rumqtt = "*"
redis = "0.9"
redis_context = { git = "https://github.com/Terkwood/prawnalith/", branch = "unstable" }
redis_delta = { git = "https://github.com/Terkwood/prawnalith/", branch = "unstable" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
uuid = { version = "0.7", features = ["v4", "v5"] }
