version: '3'
services:
  pond:
    image: "prawnalith/pond:latest"
    build: "pond/."
    labels:
      autoheal: "true"
    ports:
      - "443:8000"
    volumes:
      - "/var/volumes/pond:/data"
    depends_on:
      - "redis"
  autoheal:
    image: "willfarrell/autoheal"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always
  redis:
    image: "redis"
    volumes:
      - "/var/volumes/redis:/data"
