version: '3'
services:
  stream:
    image: "prawnalith/video:init"
    build: "gstreamer/."
  pond:
    image: "prawnalith/pond:latest"
    ports:
      - "443:8000"
    volumes:
      - "/var/volumes/pond:/data"
    depends_on:
      - "redis"
  redis:
    image: "redis"
    volumes:
      - "/var/volumes/redis:/data"
