version: '3'
services:
  redis:
    image: "redis" 
    ports:
      - "63797:6379"
    volumes:
      - "/home/$USER/volumes/redis:/data"
    environment:
      - USER:${USER}  # write this in your .env file
