/// represents an external device id.
/// these are generated by the DS18B20 and
/// can be used to find namespaced (v5) UUIDs
/// for both the temp sensor itself, as well
/// as the pH sensor which is attached to this device
#[derive(FromForm)]
pub struct ExtId {
    pub ext_id: String,
    pub device_type: String,
}

/// Represents a pH calibration with low and high
/// reference values.  Each reference value maps
/// to a millivolt reading from an SEN0169 pH meter.
/// These are used to construct the linear scale
/// which will provide the pH reading at the microcontroller.
#[derive(Debug)]
pub struct PhCalibration {
    pub low: PhRefValue,
    pub hi: PhRefValue,
}

impl PhCalibration {
    pub fn as_csv(&self) -> String {
        format!(
            "low_ph_ref,low_mv,hi_ph_ref,hi_mv\n{:.*},{:.*},{:.*},{:.*}\n",
            2, self.low.ph_ref, 2, self.low.mv, 2, self.hi.ph_ref, 2, self.hi.mv,
        )
    }
}

#[derive(Debug)]
pub struct PhRefValue {
    pub ph_ref: f32, // pH reference level
    pub mv: f32,     // millivolt reading
}
